# Generated by Django 4.0.1 on 2022-01-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_serwis', '0005_alter_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='address',
        ),
    ]
